name: App Deploy

on:
  workflow_run:
    workflows: ["Helm Deploy"]
    types: [completed]

concurrency:
  group: app-main
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::751948409182:role/github-actions-role
          aws-region: ap-northeast-1
          
      ##################################
      # SSM取得
      ##################################
      - name: Fetch Parameters
        run: |
          CLUSTER_NAME=$(aws ssm get-parameter \
            --name "/app/eks/cluster_name" \
            --query "Parameter.Value" \
            --output text)

          ECR_REPOSITORY=$(aws ssm get-parameter \
            --name "/app/ecr/repository" \
            --query "Parameter.Value" \
            --output text)

          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_ENV

      ##################################
      # ECR Login
      ##################################
      - name: Login to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      ##################################
      # Build & Push
      ##################################
      - name: Build & Push
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

          docker build -t $IMAGE_URI ./app
          docker push $IMAGE_URI

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      ##################################
      # kubeconfig
      ##################################
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name $CLUSTER_NAME \
            --region $AWS_REGION

      ##################################
      # Deploy
      ##################################
      - name: Deploy
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/web-app web-app=$IMAGE_URI