name: Terraform Deploy

on:
  push:
    branches: [ "main" ]

concurrency:
  group: terraform-main
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init
        working-directory: ./IaC

      - name: Plan
        run: terraform plan -lock-timeout=300s
        working-directory: ./IaC

      - name: Apply
        run: terraform apply -auto-approve
        working-directory: ./IaC